In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder , StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Perceptron

In [4]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [17]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers , datasets
from tensorflow.keras.utils import to_categorical

In [19]:
(X_train, y_train), (X_test, y_test) = datasets.mnist.load_data()

In [21]:
X_train.shape

(60000, 28, 28)

In [23]:
y_train.shape

(60000,)

In [27]:
X_test.shape

(10000, 28, 28)

In [26]:
X_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

## Scaling image data

In [29]:
X_train_sc = X_train.astype('float32') / 255.0
X_test_sc = X_test.astype('float32') / 255.0

In [31]:
X_train_sc[0]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

In [39]:
no_class = np.unique(y_train).shape[0]
no_class

10

In [44]:
y_train # label encoded , so sparse categorical loss

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

## Reshaping for CNN

In [33]:
X_train = X_train_sc.reshape(-1, 28, 28, 1)  # (60000, 28, 28, 1)
X_test = X_test_sc.reshape(-1, 28, 28, 1)
X_train.shape

(60000, 28, 28, 1)

In [50]:
model = Sequential([
    layers.Input(shape=(28, 28, 1)),
    
    layers.Conv2D( filters = 32,
    kernel_size = (3,3),
    activation='relu',
    strides=(1, 1),
    padding='valid',),

    layers.MaxPool2D( pool_size=(2, 2),
    padding='valid',),

    layers.Conv2D( filters = 64,
    kernel_size = (3,3),
    activation='relu',             
    strides=(1, 1),
    padding='valid',),

    layers.MaxPool2D( pool_size=(2, 2),
    padding='valid',),

    layers.Flatten(),

    layers.Dense(64, activation='relu'),

    layers.Dense(units=no_class, activation='softmax')
])

In [52]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d_4 (Conv2D)                    │ (None, 26, 26, 32)          │             320 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_4 (MaxPooling2D)       │ (None, 13, 13, 32)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_5 (Conv2D)                    │ (None, 11, 11, 64)          │          18,496 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_5 (MaxPooling2D)       │ (None, 5, 5, 64)            │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (None, 1600)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 64)                  │         102,464 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 10)                  │             650 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 121,930 (476.29 KB)

 Trainable params: 121,930 (476.29 KB)

 Non-trainable params: 0 (0.00 B)

In [53]:
model.compile(optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']          
)

In [54]:
model.fit( x=X_train,
    y=y_train,
    batch_size=32,
    epochs=10,
    verbose='auto',
    validation_split=0.2,)

Epoch 1/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - accuracy: 0.9496 - loss: 0.1682 - val_accuracy: 0.9827 - val_loss: 0.0610
Epoch 2/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.9829 - loss: 0.0545 - val_accuracy: 0.9837 - val_loss: 0.0542
Epoch 3/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.9880 - loss: 0.0377 - val_accuracy: 0.9833 - val_loss: 0.0584
Epoch 4/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.9908 - loss: 0.0276 - val_accuracy: 0.9883 - val_loss: 0.0401
Epoch 5/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.9928 - loss: 0.0211 - val_accuracy: 0.9873 - val_loss: 0.0465
Epoch 6/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - accuracy: 0.9951 - loss: 0.0154 - val_accuracy: 0.9908 - val_loss: 0.0358
Epoch 7/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.9956 - loss: 0.0133 - val_accuracy: 0.9882 - val_loss: 0.0491
Epoch 8/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.9966 - loss: 0.0104 - 

In [55]:
model.evaluate(X_test, y_test )

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9907 - loss: 0.0364   


[0.036358632147312164, 0.9907000064849854]

In [59]:
y_pred = model.predict(X_test)
y_pred

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step 


array([[3.4987016e-15, 1.8697115e-11, 6.3642728e-12, ..., 1.0000000e+00,
        2.2996921e-15, 1.0137911e-11],
       [4.8543569e-10, 3.1064193e-11, 1.0000000e+00, ..., 6.7028566e-13,
        4.0312886e-09, 9.6915104e-14],
       [5.1676288e-11, 9.9999976e-01, 8.8129636e-11, ..., 8.2455793e-09,
        2.1779127e-09, 5.4114883e-11],
       ...,
       [1.2962650e-23, 2.2746606e-15, 1.0601695e-17, ..., 4.6285599e-15,
        4.9411362e-15, 3.3896999e-15],
       [5.5943227e-15, 2.6955723e-17, 8.4662153e-19, ..., 1.7166607e-18,
        1.9183468e-09, 2.0777671e-13],
       [1.5947219e-08, 1.5527119e-14, 6.4962069e-10, ..., 6.4400794e-16,
        9.5007624e-10, 6.1886618e-13]], dtype=float32)

In [60]:
y_pred = np.argmax(y_pred, axis=1)
y_pred

array([7, 2, 1, ..., 4, 5, 6])

In [62]:
accuracy = np.mean(y_pred == y_test)
print("Test accuracy:", accuracy)


Test accuracy: 0.9907


In [63]:
cm= confusion_matrix(y_test, y_pred)

print(cm)


[[ 977    0    0    0    1    0    0    1    1    0]
 [   1 1131    0    1    0    0    0    2    0    0]
 [   1    1 1017    1    2    0    1    4    5    0]
 [   0    0    0 1006    0    3    0    0    1    0]
 [   0    0    0    0  980    0    0    0    0    2]
 [   2    0    0    6    0  879    2    0    1    2]
 [   3    2    0    0    2    2  949    0    0    0]
 [   0    3    2    1    2    0    0 1018    0    2]
 [   4    0    3    1    0    1    0    1  961    3]
 [   0    1    1    0    9    3    0    4    2  989]]
